#ifndef CONSTANTS_H
#define CONSTANTS_H


#define DEFAULT_HOSTNAME "localhost"
#define DEFAULT_PORT "58013" // 5800 + GROUP NUMBER

#define PLID_MAX_SIZE 6
#define MAX_PLAYTIME 600
#define MAX_PLAYTIME_DIGITS 3

#define MAX_FNAME 24
#define MAX_FSIZE 1024
#define MAX_TRANSMISSION 4

#define BUFFER_SIZE 128

#define PROTOCOL_ERROR "ERR"
#define SOCKETS_UDP_TIMEOUT 5

#define MAX_TRIALS 8

#endif